# Generated by Django 4.2 on 2024-10-14 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teacherrole_teacherprofile_staffprofile'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(related_name='classes_taught', to='users.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='users.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(related_name='subjects_taught', to='users.teacherprofile'),
        ),
    ]
